### ISSUE TITLE
;     Missing label for #=

### ISSUE THREAD

**Issue by jgarte** [s-expressionists/Cyclosis#4]
```
; compiling file "/gnu/store/g2pdpika72lji3md5idc2zsgpcp3ldc9-sbcl-cyclosis-0.0.0-0.eca58ea/share/common-lisp/sbcl/cyclosis/Code/packages.lisp" (written 01 JAN 1970 12:00:00 AM):
;
; caught ERROR:
;   READ error during COMPILE-FILE:
;
;     Missing label for #=
;
;       Line: 110, Column: 7, File-Position: 2924
;
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /gnu/store/g2pdpika72lji3md5idc2zsgpcp3ldc9-sbcl-cyclosis-0.0.0-0.eca58ea/share/common-lisp/sbcl/cyclosis/Code/packages.lisp" {1005331AA3}>

; compilation aborted after 0:00:00.001
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                          {1001360003}>:
  COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "cyclosis" "packages">

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1001360003}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {10053544B3}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {10053544B3}>)
2: (INVOKE-DEBUGGER #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {10053544B3}>)
3: (ERROR UIOP/LISP-BUILD:COMPILE-FILE-ERROR :CONTEXT-FORMAT "~/asdf-action::format-action/" :CONTEXT-ARGUMENTS
((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "cyclosis" "packages">)))
4: (UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS NIL T T "~/asdf-action::format-action/" ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "cyclosis" "packages">)))
5: ((SB-PCL::EMF ASDF/ACTION:PERFORM) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "cyclosis" "packages">)
6: ((LAMBDA NIL :IN ASDF/ACTION:CALL-WHILE-VISITING-ACTION))
7: ((:METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS :AROUND (T T)) #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/LISP-ACTION
```

https://github.com/s-expressionists/Cyclosis/blob/master/Code/packages.lisp#L6

**Comment by jgarte** [comment]
Hi, do you happen to know why line 6 causes my build to fail? I'm trying to package this library for GNU Guix.

**Comment by robert-strandh** [comment]
There should be a #1# rather than a #=# at the end I think.  I am not sure why it has gone unnoticed.

**Comment by robert-strandh** [comment]
Oh, I think it has gone unnoticed because it has been built only as an intrinsic library.
I am not sure what one would do with it as an extrinsic library.

**Comment by jgarte** [comment]
@robert-strandh Where can I read more about extrinsic versus intrinsic libraries?

clhs?

**Comment by robert-strandh** [comment]
I think I invented those terms.  When we build external libraries that are mainly
meant to be part of SICL or of any other new Common Lisp implementation, we
need a way to test those libraries on a mature existing Common Lisp implementation.
There is a word "cross", but it is not an adjective, and there is no term that I know
for the opposite.  So I started using "intrinsic" for "not cross", and "extrinsic" for "cross".

I agree with Alex that you may want to come to #sicl on Libera to talk more about these
things.  There are people from all over the world there, so even if I am not there,
someone is usually available to answer questions.

**Comment by yitzchak** [comment]
I've merged extrinsic support. On SBCL it will directly use sb-posix calls to implement CL:OPEN. On other implementations it will wrap the existing CL:OPEN return with Cylosis' Gray streams. ansi-test passes on the extrinsic system with the currently very minimal support for external-format (utf-8).
